name: JAVA CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v2
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
      - name: Build
        uses: ci/build-app.sh
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Build
    steps:
      - name: Test
        uses: ci/unit-test-app.sh
  Upload:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Test
    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .